### ISSUE TITLE
Здравствуйте, возникла проблема после билда

### ISSUE THREAD

**Issue by FlimixST** [jutsuper/jutsuper#1]
После того как я сбилдил всё и установил расширение в браузер, у меня появились вот эти ошибки

![image](https://github.com/jutsuper/jutsuper/assets/57029290/3174d4f5-806a-40ea-a4d4-12a2d0ec46eb)
![image](https://github.com/jutsuper/jutsuper/assets/57029290/b2daefb3-9811-43e4-9fbf-9ecea4378226)

Использовал Windows 10
Node/NPM версии
![image](https://github.com/jutsuper/jutsuper/assets/57029290/9d665e58-e9ea-4012-a07c-712300b9a118)

**Comment by kerdl** [comment]
Эта штука пока в потной разработке, но конкретно эту проблему недавно пофиксил. Просто удалил этот импорт. Можно склонировать и пересобрать ещё раз.

**Comment by FlimixST** [comment]
Спасибо за ответ, я так и сделал как вы сказали и всё заработало. Хотел бы ещё отметить 1 баг, после запуска новой серии и открытия в фулл скрин, на экране остаётся вот эта штука.
![image](https://github.com/jutsuper/jutsuper/assets/57029290/0b7a656b-c516-418f-838e-001e2b3ac21c)


И ещё, было бы хорошо если бы вы добавили авто запуск серии, потому что пока я этого не заметил

**Comment by FlimixST** [comment]
Это конечно можно выключить на самом сайте, но всё же будет костыль xD, да и много кто этим пользуется

**Comment by kerdl** [comment]
> Спасибо за ответ, я так и сделал как вы сказали и всё заработало. Хотел бы ещё отметить 1 баг, после запуска новой серии и открытия в фулл скрин, на экране остаётся вот эта штука. ![image](https://private-user-images.githubusercontent.com/57029290/322427407-0b7a656b-c516-418f-838e-001e2b3ac21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzcwNzcsIm5iZiI6MTcxMzE3Njc3NywicGF0aCI6Ii81NzAyOTI5MC8zMjI0Mjc0MDctMGI3YTY1NmItYzUxNi00MThmLTgzOGUtMDAxZTJiM2FjMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OTdlMTY2MmRlZGQ4NDc0OGQyODQ1MmRjZjFlNTQxMzhmODliZTVmM2M1NDYzZTk0MGMyNTMwMTM2YmU5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ohulWLQ_07qFCQMKYfPTSGf1maqLN6uxf1kW-QV36U)
> 
> И ещё, было бы хорошо если бы вы добавили авто запуск серии, потому что пока я этого не заметил

Хм, что за серия на скрине?

А автозапуск не работает скорее всего потому что в настройках сайта выключен
![word-image-275942-5](https://github.com/jutsuper/jutsuper/assets/91847204/4247e1b1-6cb3-4fee-91a4-c48982b98bd8)

Для расширений нет апишек чтобы разрешить автоплей, так что придётся включать вручную, но это один раз

**Comment by kerdl** [comment]
Ок, спс, попозже гляну, попытаюсь всё пофиксить

**Comment by FlimixST** [comment]
Здравствуйте. Хотел бы предложить функцию 1 из Jutsu Plus, этой функции я раньше ни в 1 расширении не видел, а она то реально полезная, не хочется как-то покупать JutSu Plus только ради неё

![image](https://github.com/jutsuper/jutsuper/assets/57029290/8a8cf9cc-2531-48e5-9532-d278e8ab46f2)

**Comment by kerdl** [comment]
> Здравствуйте. Хотел бы предложить функцию 1 из Jutsu Plus, этой функции я раньше ни в 1 расширении не видел, а она то реально полезная, не хочется как-то покупать JutSu Plus только ради неё
> 
> ![image](https://private-user-images.githubusercontent.com/57029290/323029357-8a8cf9cc-2531-48e5-9532-d278e8ab46f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzQyMDUsIm5iZiI6MTcxMzM3MzkwNSwicGF0aCI6Ii81NzAyOTI5MC8zMjMwMjkzNTctOGE4Y2Y5Y2MtMjUzMS00OGU1LTk1MzItZDI3OGU4YWI0NmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE3MTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NDAwNmE1ZTQzZWMxYzUzNDk5ODgxM2Y2NjhhYWM1OWYxNTkxOGE5MjU4MDg2ZmUxZjVmMWVhODIxY2QyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XzugyHyRqXD-WnF3-eWDNEVPrgP_PVcs7VgEbe9Xkv0)

Ок, сделаю

**Comment by kerdl** [comment]
> Здравствуйте. Хотел бы предложить функцию 1 из Jutsu Plus, этой функции я раньше ни в 1 расширении не видел, а она то реально полезная, не хочется как-то покупать JutSu Plus только ради неё
> 
> ![image](https://private-user-images.githubusercontent.com/57029290/323029357-8a8cf9cc-2531-48e5-9532-d278e8ab46f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzgzODUsIm5iZiI6MTcxNTAzODA4NSwicGF0aCI6Ii81NzAyOTI5MC8zMjMwMjkzNTctOGE4Y2Y5Y2MtMjUzMS00OGU1LTk1MzItZDI3OGU4YWI0NmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDIzMjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGMwNTY1ZjFiZjY4Y2VhZDRlNGI0NGI2YWY4NWI4MzI5MDc4NDExYzNmNzU5ZmM5ODFmMGEwYTNiMmFiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-8egH3OakdhdeqsBnhzqeWmiDrkZd3xLNdyrNRwrSk)

Заебашил, оказалось нужна буквально одна строчка в консоли `const plus_settings = { sound: false }`
Можно клонировать и тестить

**Comment by kerdl** [comment]
> Спасибо за ответ, я так и сделал как вы сказали и всё заработало. Хотел бы ещё отметить 1 баг, после запуска новой серии и открытия в фулл скрин, на экране остаётся вот эта штука. ![image](https://private-user-images.githubusercontent.com/57029290/322427407-0b7a656b-c516-418f-838e-001e2b3ac21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzgzODUsIm5iZiI6MTcxNTAzODA4NSwicGF0aCI6Ii81NzAyOTI5MC8zMjI0Mjc0MDctMGI3YTY1NmItYzUxNi00MThmLTgzOGUtMDAxZTJiM2FjMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDIzMjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllM2MwNTg0Mzk1NWRlZTFhOGZiMTYwMTYxMDAzOTdmMDJlZjk3YjM5OTNkYzc3ZDk1ZjE2M2Y0Mjg2ZDYyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KuforDfqhKLcLx_a_XEQyagrrLgl1pzjWPuZhbxrOHA)
> 
> И ещё, было бы хорошо если бы вы добавили авто запуск серии, потому что пока я этого не заметил

Этого, кстати, у меня так и не получилось добиться, так что если есть возможность, очень помог бы видос с этим поведением и открытой консолью
